package net.vietnamvisaonarrival.model;

// default package
// Generated Nov 20, 2014 8:56:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * CategoryHasNewsId generated by hbm2java
 */
public class CategoryHasNewsId implements java.io.Serializable {

	private int categoryCategoryId;
	private int newsNewsId;

	public CategoryHasNewsId() {
	}

	public CategoryHasNewsId(int categoryCategoryId, int newsNewsId) {
		this.categoryCategoryId = categoryCategoryId;
		this.newsNewsId = newsNewsId;
	}

	public int getCategoryCategoryId() {
		return this.categoryCategoryId;
	}

	public void setCategoryCategoryId(int categoryCategoryId) {
		this.categoryCategoryId = categoryCategoryId;
	}

	public int getNewsNewsId() {
		return this.newsNewsId;
	}

	public void setNewsNewsId(int newsNewsId) {
		this.newsNewsId = newsNewsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryHasNewsId))
			return false;
		CategoryHasNewsId castOther = (CategoryHasNewsId) other;

		return (this.getCategoryCategoryId() == castOther
				.getCategoryCategoryId())
				&& (this.getNewsNewsId() == castOther.getNewsNewsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCategoryCategoryId();
		result = 37 * result + this.getNewsNewsId();
		return result;
	}

}
