package net.vietnamvisaonarrival.model;
// default package
// Generated Nov 20, 2014 8:56:40 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private int paymentId;
	private String paymentType;
	private BigDecimal amount;
	private String status;

	public Payment() {
	}

	public Payment(int paymentId) {
		this.paymentId = paymentId;
	}

	public Payment(int paymentId, String paymentType, BigDecimal amount,
			String status) {
		this.paymentId = paymentId;
		this.paymentType = paymentType;
		this.amount = amount;
		this.status = status;
	}

	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
