package net.vietnamvisaonarrival.model;
// default package
// Generated Nov 20, 2014 8:56:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * PaymentofOrder generated by hbm2java
 */
public class PaymentofOrder implements java.io.Serializable {

	private Integer paymentOrderId;
	private int paymentPaymentId;
	private int orderOrderId;
	private int orderStatusOrderStatusId;

	public PaymentofOrder() {
	}

	public PaymentofOrder(int paymentPaymentId, int orderOrderId,
			int orderStatusOrderStatusId) {
		this.paymentPaymentId = paymentPaymentId;
		this.orderOrderId = orderOrderId;
		this.orderStatusOrderStatusId = orderStatusOrderStatusId;
	}

	public Integer getPaymentOrderId() {
		return this.paymentOrderId;
	}

	public void setPaymentOrderId(Integer paymentOrderId) {
		this.paymentOrderId = paymentOrderId;
	}

	public int getPaymentPaymentId() {
		return this.paymentPaymentId;
	}

	public void setPaymentPaymentId(int paymentPaymentId) {
		this.paymentPaymentId = paymentPaymentId;
	}

	public int getOrderOrderId() {
		return this.orderOrderId;
	}

	public void setOrderOrderId(int orderOrderId) {
		this.orderOrderId = orderOrderId;
	}

	public int getOrderStatusOrderStatusId() {
		return this.orderStatusOrderStatusId;
	}

	public void setOrderStatusOrderStatusId(int orderStatusOrderStatusId) {
		this.orderStatusOrderStatusId = orderStatusOrderStatusId;
	}

}
