package net.vietnamvisaonarrival.action;

import java.util.ArrayList;
import java.util.List;

public class Data {
private List<String> strListCountry;
private List<String> strDiffCountry;
public List<String> getStrDiffCountry() {
	return strDiffCountry;
}
Data ()
{ 
strListCountry = new ArrayList<String>();
strListCountry.add("China");
strListCountry.add("United Kingdom");
strListCountry.add("Afghanistan");
strListCountry.add("Albania");
strListCountry.add("Algeria");
strListCountry.add("Andorra");
strListCountry.add("Angola");
strListCountry.add("Antigua & Deps");
strListCountry.add("Argentina");
strListCountry.add("Armenia");
strListCountry.add("Australia");
strListCountry.add("Austria");
strListCountry.add("Azerbaijan");
strListCountry.add("Bahamas");
strListCountry.add("Bahrain");
strListCountry.add("Bangladesh");
strListCountry.add("Barbados");
strListCountry.add("Belarus");
strListCountry.add("Belgium");
strListCountry.add("Belize");
strListCountry.add("Benin");
strListCountry.add("Bhutan");
strListCountry.add("Bolivia");
strListCountry.add("Bosnia Herzegovina");
strListCountry.add("Botswana");
strListCountry.add("Brazil");
strListCountry.add("Brunei");
strListCountry.add("Bulgaria");
strListCountry.add("Burkina");
strListCountry.add("Burundi");
strListCountry.add("Cambodia");
strListCountry.add("Cameroon");
strListCountry.add("Canada");
strListCountry.add("Cape Verde");
strListCountry.add("Central African Rep");
strListCountry.add("Chad");
strListCountry.add("Chile");
strListCountry.add("Colombia");
strListCountry.add("Comoros");
strListCountry.add("Congo");
strListCountry.add("Congo {Democratic Rep}");
strListCountry.add("Costa Rica");
strListCountry.add("Croatia");
strListCountry.add("Cuba");
strListCountry.add("Cyprus");
strListCountry.add("Czech Republic");
strListCountry.add("Denmark");
strListCountry.add("Djibouti");
strListCountry.add("Dominica");
strListCountry.add("Dominican Republic");
strListCountry.add("East Timor");
strListCountry.add("Ecuador");
strListCountry.add("Egypt");
strListCountry.add("El Salvador");
strListCountry.add("Equatorial Guinea");
strListCountry.add("Eritrea");
strListCountry.add("Estonia");
strListCountry.add("Ethiopia");
strListCountry.add("Fiji");
strListCountry.add("Finland");
strListCountry.add("France");
strListCountry.add("Gabon");
strListCountry.add("Gambia");
strListCountry.add("Georgia");
strListCountry.add("Germany");
strListCountry.add("Ghana");
strListCountry.add("Greece");
strListCountry.add("Grenada");
strListCountry.add("Guatemala");
strListCountry.add("Guinea");
strListCountry.add("Guinea-Bissau");
strListCountry.add("Guyana");
strListCountry.add("Haiti");
strListCountry.add("Honduras");
strListCountry.add("Hungary");
strListCountry.add("Iceland");
strListCountry.add("India");
strListCountry.add("Indonesia");
strListCountry.add("Iran");
strListCountry.add("Iraq");
strListCountry.add("Ireland {Republic}");
strListCountry.add("Israel");
strListCountry.add("Italy");
strListCountry.add("Ivory Coast");
strListCountry.add("Jamaica");
strListCountry.add("Japan");
strListCountry.add("Jordan");
strListCountry.add("Kazakhstan");
strListCountry.add("Kenya");
strListCountry.add("Kiribati");
strListCountry.add("Korea North");
strListCountry.add("Korea South");
strListCountry.add("Kosovo");
strListCountry.add("Kuwait");
strListCountry.add("Kyrgyzstan");
strListCountry.add("Laos");
strListCountry.add("Latvia");
strListCountry.add("Lebanon");
strListCountry.add("Lesotho");
strListCountry.add("Liberia");
strListCountry.add("Libya");
strListCountry.add("Liechtenstein");
strListCountry.add("Lithuania");
strListCountry.add("Luxembourg");
strListCountry.add("Macedonia");
strListCountry.add("Madagascar");
strListCountry.add("Malawi");
strListCountry.add("Malaysia");
strListCountry.add("Maldives");
strListCountry.add("Mali");
strListCountry.add("Malta");
strListCountry.add("Marshall Islands");
strListCountry.add("Mauritania");
strListCountry.add("Mauritius");
strListCountry.add("Mexico");
strListCountry.add("Micronesia");
strListCountry.add("Moldova");
strListCountry.add("Monaco");
strListCountry.add("Mongolia");
strListCountry.add("Montenegro");
strListCountry.add("Morocco");
strListCountry.add("Mozambique");
strListCountry.add("Myanmar, {Burma}");
strListCountry.add("Namibia");
strListCountry.add("Nauru");
strListCountry.add("Nepal");
strListCountry.add("Netherlands");
strListCountry.add("New Zealand");
strListCountry.add("Nicaragua");
strListCountry.add("Niger");
strListCountry.add("Nigeria");
strListCountry.add("Norway");
strListCountry.add("Oman");
strListCountry.add("Pakistan");
strListCountry.add("Palau");
strListCountry.add("Panama");
strListCountry.add("Papua New Guinea");
strListCountry.add("Paraguay");
strListCountry.add("Peru");
strListCountry.add("Philippines");
strListCountry.add("Poland");
strListCountry.add("Portugal");
strListCountry.add("Qatar");
strListCountry.add("Romania");
strListCountry.add("Russian Federation");
strListCountry.add("Rwanda");
strListCountry.add("St Kitts & Nevis");
strListCountry.add("St Lucia");
strListCountry.add("Saint Vincent & the Grenadines");
strListCountry.add("Samoa");
strListCountry.add("San Marino");
strListCountry.add("Sao Tome & Principe");
strListCountry.add("Saudi Arabia");
strListCountry.add("Senegal");
strListCountry.add("Serbia");
strListCountry.add("Seychelles");
strListCountry.add("Sierra Leone");
strListCountry.add("Singapore");
strListCountry.add("Slovakia");
strListCountry.add("Slovenia");
strListCountry.add("Solomon Islands");
strListCountry.add("Somalia");
strListCountry.add("South Africa");
strListCountry.add("South Sudan");
strListCountry.add("Spain");
strListCountry.add("Sri Lanka");
strListCountry.add("Sudan");
strListCountry.add("Suriname");
strListCountry.add("Swaziland");
strListCountry.add("Sweden");
strListCountry.add("Switzerland");
strListCountry.add("Syria");
strListCountry.add("Taiwan");
strListCountry.add("Tajikistan");
strListCountry.add("Tanzania");
strListCountry.add("Thailand");
strListCountry.add("Togo");
strListCountry.add("Tonga");
strListCountry.add("Trinidad & Tobago");
strListCountry.add("Tunisia");
strListCountry.add("Turkey");
strListCountry.add("Turkmenistan");
strListCountry.add("Tuvalu");
strListCountry.add("Uganda");
strListCountry.add("Ukraine");
strListCountry.add("United Arab Emirates");
strListCountry.add("Uruguay");
strListCountry.add("Uzbekistan");
strListCountry.add("Vanuatu");
strListCountry.add("Vatican City");
strListCountry.add("Venezuela");
strListCountry.add("Vietnam");
strListCountry.add("Yemen");
strListCountry.add("Zambia");
strListCountry.add("Zimbabwe");
// Difficult country
strDiffCountry = new ArrayList<String>();
strDiffCountry.add("China");
strDiffCountry.add("India");
}
public void setStrDiffCountry(List<String> strDiffCountry) {
	this.strDiffCountry = strDiffCountry;
}
public List<String> getStrListCountry() {
	return strListCountry;
}
public void setStrListCountry(List<String> strCountry) {
	this.strListCountry = strCountry;
}



}
