// default package
// Generated Nov 21, 2014 9:23:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * CategoryHasNews generated by hbm2java
 */
public class CategoryHasNews implements java.io.Serializable {

	private CategoryHasNewsId id;

	public CategoryHasNews() {
	}

	public CategoryHasNews(CategoryHasNewsId id) {
		this.id = id;
	}

	public CategoryHasNewsId getId() {
		return this.id;
	}

	public void setId(CategoryHasNewsId id) {
		this.id = id;
	}

}
