// default package
// Generated Nov 21, 2014 9:23:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private NewsId id;
	private Date dateCreate;
	private Date dateUpdated;
	private String author;
	private String content;
	private Integer categoryId;
	private String tag;
	private String meta;
	private String newsTitle;
	private String newscol;
	private String countA;
	private String countB;
	private int userUserId;

	public News() {
	}

	public News(NewsId id, int userUserId) {
		this.id = id;
		this.userUserId = userUserId;
	}

	public News(NewsId id, Date dateCreate, Date dateUpdated, String author,
			String content, Integer categoryId, String tag, String meta,
			String newsTitle, String newscol, String countA, String countB,
			int userUserId) {
		this.id = id;
		this.dateCreate = dateCreate;
		this.dateUpdated = dateUpdated;
		this.author = author;
		this.content = content;
		this.categoryId = categoryId;
		this.tag = tag;
		this.meta = meta;
		this.newsTitle = newsTitle;
		this.newscol = newscol;
		this.countA = countA;
		this.countB = countB;
		this.userUserId = userUserId;
	}

	public NewsId getId() {
		return this.id;
	}

	public void setId(NewsId id) {
		this.id = id;
	}

	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public String getMeta() {
		return this.meta;
	}

	public void setMeta(String meta) {
		this.meta = meta;
	}

	public String getNewsTitle() {
		return this.newsTitle;
	}

	public void setNewsTitle(String newsTitle) {
		this.newsTitle = newsTitle;
	}

	public String getNewscol() {
		return this.newscol;
	}

	public void setNewscol(String newscol) {
		this.newscol = newscol;
	}

	public String getCountA() {
		return this.countA;
	}

	public void setCountA(String countA) {
		this.countA = countA;
	}

	public String getCountB() {
		return this.countB;
	}

	public void setCountB(String countB) {
		this.countB = countB;
	}

	public int getUserUserId() {
		return this.userUserId;
	}

	public void setUserUserId(int userUserId) {
		this.userUserId = userUserId;
	}

}
