// default package
// Generated Nov 21, 2014 9:23:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrderStatus generated by hbm2java
 */
public class OrderStatus implements java.io.Serializable {

	private Integer orderStatusId;
	private String customerName;
	private String status;
	private String orderStatuscol;
	private String statusCode;

	public OrderStatus() {
	}

	public OrderStatus(String customerName, String status,
			String orderStatuscol, String statusCode) {
		this.customerName = customerName;
		this.status = status;
		this.orderStatuscol = orderStatuscol;
		this.statusCode = statusCode;
	}

	public Integer getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(Integer orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getOrderStatuscol() {
		return this.orderStatuscol;
	}

	public void setOrderStatuscol(String orderStatuscol) {
		this.orderStatuscol = orderStatuscol;
	}

	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

}
